# Generated by Django 5.0.1 on 2024-01-17 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='answer',
            new_name='about_yourself',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.AddField(
            model_name='response',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 15, 44, 4, 954992, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
