# Generated by Django 5.0.1 on 2024-01-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_answer_response_about_yourself_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.CharField(default='Default Question', max_length=255),
            preserve_default=False,
        ),
    ]
